---
- name: MySQL Provisioning Playbook
  hosts: website
  become: true
  vars:
    mysql_user: "{{ mysql_username }}"
    mysql_password: "{{ mysql_password }}"
    mysql_host: "{{ mysql_host | default('localhost') }}"
    mysql_port: "{{ mysql_port | default('3306') }}"
    mysql_db: "{{ mysql_database }}"

  tasks:
    - name: Check if MySQL command file exists
      ansible.builtin.stat:
        path: files/mysqlProvision.txt
      register: mysql_commands_file
      delegate_to: localhost

    - name: Fail if MySQL command file is missing
      ansible.builtin.fail:
        msg: "Required MySQL commands file 'files/mysqlProvision.txt' not found!"
      when: not mysql_commands_file.stat.exists

    - name: Install required Python MySQL library
      ansible.builtin.pip:
        name: PyMySQL
        state: present

    - name: Execute MySQL commands from file
      community.mysql.mysql_db:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
        login_port: "{{ mysql_port }}"
        state: import
        name: "{{ mysql_db }}"
        target: files/mysqlProvision.txt
      register: mysql_import_result

    - name: Display MySQL import results
      ansible.builtin.debug:
        var: mysql_import_result
        verbosity: 1
