---
- name: MySQL Provisioning Playbook
  hosts: website
  become: yes
  vars:
    mysql_user: "{{ mysql_username }}"
    mysql_password: "{{ mysql_password }}"
    mysql_host: "{{ mysql_host | default('localhost') }}"
    mysql_port: "{{ mysql_port | default('3306') }}"
    mysql_db: "{{ mysql_database }}"
    temp_sql_path: "/tmp/mysqlProvision.txt"

  tasks:
    - name: Copy MySQL commands file to the remote server
      copy:
        src: "../files/mysqlProvision.txt"
        dest: "{{ temp_sql_path }}"
        mode: '0600'
      
    - name: Ensure mysql-client is installed
      package:
        name: mysql-client
        state: present
      ignore_errors: yes  # Some distros might use different package name
    
    - name: Execute MySQL commands using command line
      shell: >
        mysql -u {{ mysql_user }} 
        -p'{{ mysql_password }}' 
        -h {{ mysql_host }} 
        -P {{ mysql_port }} 
        {{ mysql_db }} < {{ temp_sql_path }}
      no_log: false  # Hide sensitive output
      register: mysql_import_result
      
    - name: Display MySQL import status
      debug:
        msg: "MySQL import completed successfully"
      when: mysql_import_result.rc == 0

    - name: Display MySQL import error
      debug:
        msg: "MySQL import failed: {{ mysql_import_result.stderr }}"
      when: mysql_import_result.rc != 0
      
    - name: Clean up temporary SQL file
      file:
        path: "{{ temp_sql_path }}"
        state: absent